### ISSUE TITLE
Development questions

### ISSUE THREAD

**Issue by nithinmurali** [adonespitogo/AdoBot#32]
Hi @adonespitogo, Thanks for developing this project, its awesome :)

I have been going through the code,  i have few questions.

1. Why did you implement http request from scratch rather than using a library like okhttp/retrofit? any specific benefits?
2. Why are you saving the call logs to database? It don't seem to be using the saved data. While sending the logs, you seem to be fetching from content Provider only.

**Comment by adonespitogo** [comment]
No particular reason. I just started learning android development when I started this project and needed basic http module I can use to send data to the server. Please feel free to send a PR :)

**Comment by nithinmurali** [comment]
Thanks @adonespitogo

**Comment by nithinmurali** [comment]
I have made a lot of chenages
