### ISSUE TITLE
Please provied compiled signed apk of asobot.

### ISSUE THREAD

**Issue by deeppatelrajkot** [adonespitogo/AdoBot#9]
Provide adobot signed apk. Please email download link me at marsonia.deep@gmail.com
Its urgent.

**Comment by adonespitogo** [comment]
I'm not your servant mr.

**Comment by adonespitogo** [comment]
https://github.com/adonespitogo/AdoBot/issues/28#issuecomment-472316608

**Comment by lexzy123** [comment]
hi, how do i get the signed copy sir, kindly assist. regards

**Comment by merabchik** [comment]
You need just build it and run server side application
